---
- block:
  - name: TMP repos.d for overcloud
    file:
        name: "{{ tmp_oc_repos_dir }}"
        state: directory

  - include_role:
        name: rhos-release
    vars:
        release: "{{ install.version|default(undercloud_version) }}"
        rr_buildmods: "{{ install.buildmods }}"
        build: "{{ install.build | default(omit) }}"
        director_build: "{{ install.get('director', {}).build|default(omit) }}"
        mirror: "{{ install.mirror | default(omit) }}"
        rr_target_directory: "{{ tmp_oc_repos_dir }}"
        rr_discover_build: yes
        rr_distro_version: "{{ install.osrelease|default(omit) }}"
        enable_testing_repos: "{{ install.get('enable', {}).get('testing', {}).repos|default(omit) }}"

  - name: Backup old repo data
    command: mv -v /etc/yum.repos.d /etc/yum.repos.d_old

  - name: Make new repo dir active
    command: mv -fu "{{ tmp_oc_repos_dir }}" /etc/

  - name: Sudoers no tty
    lineinfile:
        dest: /etc/sudoers
        state: absent
        regexp: 'Defaults\s+requiretty'

  - name: Create default user
    user:
        name: "{{ install.user.name }}"
        state: present
        password: "{{ install.user.password | password_hash('sha512') }}"

  - name: Add user to sudoers
    lineinfile:
        dest: "/etc/sudoers"
        line: "{{ install.user.name }} ALL=(root) NOPASSWD:ALL"

  - name: Create .ssh direcotry for non-root user
    file:
        path: "{{ default_privatekey | dirname }}"
        state: directory
    become_user: "{{ install.user.name }}"
    become: yes

  - set_fact:
        uc_publickey: "{{ lookup('file', local_undercloud_pubkey) }}"

  - name: Set up authorized_keys for non root user
    authorized_key:
        user: "{{ install.user.name }}"
        key: "{{ uc_publickey }}"

  - name: Install python-heat-agent package
    package:
        name: 'python-heat-agent'
        state: latest
    when: install.version|default(undercloud_version) |openstack_release < 15

  - name: Install python3-heat-agent package
    package:
        name: 'python3-heat-agent'
        state: latest
    when: install.version|default(undercloud_version) |openstack_release >= 15
  delegate_to: "{{ scale_node }}"
