an_nodes_to_add: []
an_ignore_nodes: []
# overcloud deployment script
overcloud_deploy_script: "~/overcloud_deploy.sh"
# new instackenv file
instackenv_file_name: "~/newnodes.json"
# vbmc start port
vbmc_start_port: 6230
# undercloud keys
local_undercloud_pubkey: "{{ inventory_dir }}/id_rsa_undercloud.pub"
default_privatekey: "~/.ssh/id_rsa"
default_pubkey: "{{ default_privatekey }}.pub"
# rhos-release vars
tmp_oc_repos_dir: /tmp/oc_repos/yum.repos.d
rhos_release_rpm: "https://url.corp.redhat.com/latest-rhos-release-rpm"